# Generated by Django 2.2.3 on 2019-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('data_type_id', models.IntegerField()),
                ('data_type', models.TextField(max_length=200)),
                ('data_value', models.IntegerField()),
                ('data_unit', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'stats',
                'managed': False,
            },
        ),
    ]
